### ISSUE TITLE
匯出資料如何解密？

### ISSUE THREAD

**Issue by kiang** [g0v/victim#4]
試著匯出資料後發現是經過加密的（還是這是程式錯誤？），也許需要解密的提示

**Comment by kiang** [comment]
看了一下程式碼，是壓縮之後轉為 base64 字串，但我試著 base64_decode 後透過 gz 或是 zip 解壓縮都是失敗的

**Comment by yutin1987** [comment]
version 2 為 server 建置. 不需要解碼
